//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class issued_books
    {
        public int Member_id { get; set; }
        public int Book_id { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public Nullable<System.TimeSpan> Issue_Time { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public Nullable<System.TimeSpan> Return_Time { get; set; }
    
        public virtual library_books library_books { get; set; }
        public virtual library_members library_members { get; set; }
    }
}
