//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_Member_Login
    {
        public int login_ID { get; set; }
        public string LM_username { get; set; }
        public string LM_password { get; set; }
    }
}
