//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class library_management_systemEntities : DbContext
    {
        public library_management_systemEntities()
            : base("name=library_management_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<issued_books> issued_books { get; set; }
        public virtual DbSet<Issued_Books_Record> Issued_Books_Record { get; set; }
        public virtual DbSet<library_books> library_books { get; set; }
        public virtual DbSet<Library_Member_Login> Library_Member_Login { get; set; }
        public virtual DbSet<library_members> library_members { get; set; }
        public virtual DbSet<shelf> shelves { get; set; }
    }
}
