//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class library_books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public library_books()
        {
            this.issued_books = new HashSet<issued_books>();
        }
    
        public int isbn_no { get; set; }
        public string title { get; set; }
        public string book_publisher { get; set; }
        public string C_book_author { get; set; }
        public int shelve_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<issued_books> issued_books { get; set; }
        public virtual Issued_Books_Record Issued_Books_Record { get; set; }
        public virtual shelf shelf { get; set; }
    }
}
