//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class shelf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shelf()
        {
            this.library_books = new HashSet<library_books>();
        }
    
        public int shelve_ID { get; set; }
        public string shelve_subject { get; set; }
        public int Shelve_no { get; set; }
        public int almirah_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<library_books> library_books { get; set; }
    }
}
